import type { DemoSpec } from '../builder';

export const sociedad: DemoSpec[] = [
  {
    slug: 'ciudades-planes-calor-extremo-verano',
    title: 'Las grandes ciudades preparan planes para un verano con más días de calor extremo',
    dek: 'Municipios del área metropolitana coordinan puntos de hidratación, horarios de trabajo protegidos y alertas por barrio. Las medidas todavía dependen de presupuestos que no están aprobados.',
    category: 'sociedad',
    tags: ['Calor extremo', 'Ciudades', 'Salud pública', 'Clima'],
    image: 'calor',
    minutesAgo: 50,
    updatedMinutesAgo: 20,
    priority: 5,
    status: 'verified',
    sources: [
      ['organismo', 'Borrador del protocolo de calor y cronograma de implementación.'],
      ['servicio-meteorologico', 'Perspectiva estacional de temperaturas para el trimestre.'],
      ['diario-regional', 'Relevamiento de las medidas en cada municipio.'],
      ['universidad', 'Estudio sobre islas de calor urbano en barrios densos.'],
    ],
    claims: [
      { text: 'Al menos cinco municipios firmaron el acta de coordinación del protocolo de calor.', status: 'confirmed', sources: ['organismo', 'diario-regional'] },
      { text: 'La perspectiva estacional prevé temperaturas por encima de lo normal para el trimestre.', status: 'confirmed', sources: ['servicio-meteorologico', 'universidad'] },
      { text: 'El financiamiento de los puntos de hidratación está garantizado.', status: 'unconfirmed', sources: ['organismo'] },
    ],
    updates: [{ minutesAgo: 20, text: 'Se agregó el detalle del sistema de alertas por barrio, confirmado por el organismo.' }],
    body: [
      { type: 'p', text: 'Cinco municipios del área metropolitana firmaron un acta para coordinar su respuesta ante olas de calor durante el próximo verano. El documento, al que Contraste tuvo acceso en su versión borrador, prevé puntos de hidratación en espacios públicos, cambios de horario para tareas al aire libre y un sistema de alertas segmentado por barrio.' },
      { type: 'p', text: 'La iniciativa llega después de que la perspectiva estacional del servicio meteorológico anticipara temperaturas por encima de lo normal para el trimestre. Ese pronóstico no indica cuántas olas de calor habrá ni cuándo: describe una tendencia, y así lo aclara el propio informe.' },
      {
        type: 'facts',
        confirmed: [
          'El acta de coordinación fue firmada por cinco municipios.',
          'El protocolo incluye alertas por barrio, puntos de hidratación y horarios protegidos.',
          'La perspectiva estacional prevé temperaturas superiores a lo normal.',
        ],
        unconfirmed: [
          'Cuántos puntos de hidratación habrá y dónde.',
          'Si los presupuestos municipales cubren las medidas: dos de los cinco no los aprobaron todavía.',
        ],
      },
      { type: 'h2', text: 'Qué cambia para los vecinos' },
      { type: 'p', text: 'El cambio más visible sería el sistema de alertas. Hasta ahora, los avisos por calor se emitían para toda la región; el borrador propone diferenciarlos por barrio, combinando el pronóstico con datos de densidad edilicia y cobertura de árboles. Un estudio de una universidad pública citado en el documento muestra que, en los barrios más densos, la temperatura nocturna puede quedar varios grados por encima de la de zonas con más verde.' },
      { type: 'p', text: 'Para quienes trabajan al aire libre, el protocolo recomienda reprogramar tareas en las horas de mayor temperatura. En el caso del personal municipal, la medida sería obligatoria; para el sector privado, el texto habla de recomendaciones y no establece sanciones.' },
      { type: 'h2', text: 'Lo que falta definir' },
      { type: 'p', text: 'El punto pendiente es el financiamiento. Según el relevamiento del diario regional consultado, dos de los municipios firmantes todavía no aprobaron su presupuesto para el año próximo, y el acta no especifica cuánto aportará cada uno. El organismo coordinador indicó que la distribución de costos se discutirá en una reunión técnica antes de diciembre.' },
      { type: 'note', tone: 'context', title: 'Cómo verificamos esta nota', text: 'Contrastamos el borrador del protocolo con el relevamiento municipio por municipio y con la perspectiva estacional publicada. Lo que solo figura en el borrador, como el financiamiento, lo señalamos como no confirmado.' },
    ],
  },
  {
    slug: 'alerta-tormentas-area-metropolitana-litoral',
    title: 'Rige una alerta amarilla por tormentas para el área metropolitana y parte del litoral',
    dek: 'El servicio meteorológico prevé lluvias intensas y ráfagas desde la tarde. Algunos distritos suspendieron actividades al aire libre; otros todavía no informaron medidas.',
    category: 'sociedad',
    tags: ['Tormentas', 'Alerta meteorológica', 'Clima'],
    image: 'tormenta',
    minutesAgo: 35,
    updatedMinutesAgo: 8,
    priority: 4,
    live: true,
    status: 'developing',
    sources: [
      ['servicio-meteorologico', 'Aviso de alerta amarilla y área de cobertura.'],
      ['radio-local', 'Medidas informadas por los distritos.'],
      ['agencia-nacional', 'Situación en las rutas del litoral.'],
    ],
    claims: [
      { text: 'La alerta amarilla rige desde las 15 para el área metropolitana y el sur del litoral.', status: 'confirmed', sources: ['servicio-meteorologico', 'agencia-nacional'] },
      { text: 'Hubo cortes de luz en barrios del oeste.', status: 'unconfirmed', sources: ['radio-local'] },
    ],
    updates: [
      { minutesAgo: 8, text: 'Se sumó la suspensión de clases de educación física en dos distritos, confirmada por sus áreas de educación.' },
      { minutesAgo: 22, text: 'El servicio meteorológico extendió el área de la alerta al sur del litoral.' },
    ],
    body: [
      { type: 'note', tone: 'update', title: 'Nota en desarrollo', text: 'La información puede cambiar. Actualizamos esta nota a medida que se confirman datos; el historial de cambios está al final.' },
      { type: 'p', text: 'El servicio meteorológico emitió una alerta amarilla por tormentas para el área metropolitana y el sur del litoral, vigente desde las 15. El aviso prevé lluvias intensas en períodos cortos, actividad eléctrica y ráfagas que podrían superar los 60 kilómetros por hora.' },
      { type: 'p', text: 'Dos distritos suspendieron las clases de educación física y las actividades deportivas al aire libre previstas para la tarde. El resto de los municipios del área no había informado medidas al momento de esta actualización.' },
      {
        type: 'facts',
        confirmed: ['La alerta amarilla y su horario de inicio.', 'La extensión del área de cobertura al sur del litoral.', 'La suspensión de actividades al aire libre en dos distritos.'],
        unconfirmed: ['Reportes de cortes de luz en barrios del oeste: por ahora solo los informó una radio local y la distribuidora no lo confirmó.'],
      },
      { type: 'h2', text: 'Qué recomienda el aviso' },
      { type: 'list', items: ['Evitar circular por zonas anegadas.', 'Asegurar objetos que el viento pueda desplazar.', 'No refugiarse bajo árboles durante la actividad eléctrica.', 'Consultar los avisos oficiales antes de salir a la ruta.'] },
    ],
  },
  {
    slug: 'colectivos-nuevas-frecuencias-nocturnas',
    title: 'Diez líneas de colectivo suman frecuencias nocturnas desde noviembre',
    dek: 'El cambio apunta a reducir las esperas después de la medianoche, cuando hoy pueden superar la media hora. Las empresas y la autoridad de transporte todavía discuten cómo se financian los servicios extra.',
    category: 'sociedad',
    tags: ['Transporte', 'Colectivos', 'Ciudades'],
    image: 'terminal',
    minutesAgo: 240,
    priority: 3,
    status: 'verified',
    sources: [
      ['organismo', 'Resolución con el listado de líneas y horarios.'],
      ['boletin-oficial', 'Publicación de la resolución.'],
      ['diario-regional', 'Postura de las empresas de transporte.'],
    ],
    claims: [
      { text: 'La resolución fija nuevas frecuencias nocturnas para diez líneas desde noviembre.', status: 'confirmed', sources: ['organismo', 'boletin-oficial'] },
      { text: 'Las empresas reclaman una compensación por los servicios extra.', status: 'confirmed', sources: ['diario-regional'] },
    ],
    body: [
      { type: 'p', text: 'Diez líneas de colectivo tendrán más frecuencias entre la medianoche y las cinco de la mañana a partir de noviembre, según una resolución de la autoridad de transporte publicada en el boletín oficial. En esa franja, la espera promedio en esas líneas puede superar hoy la media hora.' },
      { type: 'p', text: 'La resolución establece un intervalo máximo entre colectivos para cada línea y obliga a informar los horarios en las paradas con pantalla. No modifica recorridos ni tarifas.' },
      { type: 'h2', text: 'El costo, en discusión' },
      { type: 'p', text: 'Las cámaras que agrupan a las empresas de transporte señalaron que los servicios nocturnos tienen menos pasajeros y que necesitan una compensación para sostenerlos. La autoridad de transporte no respondió todavía cómo se cubrirá ese costo; la resolución remite a un acuerdo posterior.' },
    ],
  },
  {
    slug: 'escuelas-jornada-extendida-talleres',
    title: 'Cuarenta escuelas prueban una jornada extendida con talleres de programación y arte',
    dek: 'La experiencia dura un cuatrimestre y será evaluada por una universidad pública. Los gremios docentes piden conocer cómo se pagarán las horas adicionales.',
    category: 'sociedad',
    tags: ['Educación', 'Escuelas', 'Jornada extendida'],
    image: 'aula',
    minutesAgo: 480,
    priority: 3,
    status: 'partial',
    sources: [
      ['organismo', 'Listado de escuelas y contenidos de los talleres.'],
      ['universidad', 'Diseño de la evaluación del programa.'],
      ['radio-local', 'Posición de los gremios docentes.'],
    ],
    claims: [
      { text: 'Cuarenta escuelas participan de la prueba durante un cuatrimestre.', status: 'confirmed', sources: ['organismo', 'universidad'] },
      { text: 'Las horas adicionales se pagarán como horas cátedra.', status: 'unconfirmed', sources: ['organismo'] },
    ],
    body: [
      { type: 'p', text: 'Cuarenta escuelas primarias comenzaron una prueba de jornada extendida que suma dos horas diarias de talleres: programación, artes visuales, música y huerta. La experiencia dura un cuatrimestre y será evaluada por un equipo de una universidad pública, que medirá asistencia, participación y aprendizajes.' },
      { type: 'p', text: 'Las escuelas fueron elegidas entre las que ya tenían comedor y espacio disponible por la tarde. El organismo educativo informó que, si los resultados son favorables, el esquema podría ampliarse el año próximo.' },
      { type: 'facts', confirmed: ['La cantidad de escuelas y la duración de la prueba.', 'Que una universidad pública hará la evaluación.'], unconfirmed: ['Cómo se pagarán las horas adicionales a docentes: el organismo habló de horas cátedra, pero no hay una norma publicada.'] },
      { type: 'p', text: 'Los gremios docentes dijeron que acompañan la iniciativa pero pidieron que la forma de pago de las horas extra quede por escrito antes de que termine el primer mes.' },
    ],
  },
  {
    slug: 'demoras-trenes-corredor-oeste-obras',
    title: 'Demoras en los trenes del corredor oeste por obras programadas durante el fin de semana',
    dek: 'Los servicios funcionarán con frecuencias reducidas entre el sábado y el domingo por la renovación de vías.',
    category: 'sociedad',
    type: 'breve',
    tags: ['Transporte', 'Trenes'],
    minutesAgo: 15,
    priority: 2,
    status: 'verified',
    sources: [
      ['organismo', 'Aviso de obras y cronograma.'],
      ['radio-local', 'Confirmación de los horarios afectados.'],
    ],
    body: [
      { type: 'p', text: 'Los trenes del corredor oeste funcionarán con frecuencias reducidas el sábado y el domingo por la renovación de vías entre dos estaciones intermedias. El operador recomendó consultar los horarios actualizados antes de viajar; el servicio se normalizaría el lunes a primera hora.' },
    ],
  },
];
